---
name: Molecule testing workflow
on:
  workflow_dispatch:

jobs:
  Tox:
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set env variables
        run: |
          python3 -V | awk '{ print $NF}' | cut -c 1-4
          echo "/Users/runner/Library/Python/$(python3 -V | awk '{ print $NF}' | cut -c 1-4)/bin" >> $GITHUB_PATH
          echo "/Library/Frameworks/Python.framework/Versions/$(python3 -V | awk '{ print $NF}' | cut -c 1-4)/bin" >> $GITHUB_PATH

      - name: Install system dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --user --upgrade tox
          vagrant plugin install vagrant-vbguest

      - name: Run tox
        run: |
          tox
