---
name: Molecule testing workflow
on:
  workflow_dispatch:

jobs:
  Tox:
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set env variables
        run: |
          echo PATH="/Users/runner/Library/Python/3.10/bin:$PATH" >> $GITHUB_ENV
          echo PATH="/Users/runner/Library/Python/3.11/bin:$PATH" >> $GITHUB_ENV
          echo PATH="/Users/runner/Library/Python/3.12/bin:$PATH" >> $GITHUB_ENV
          echo PATH="/Library/Frameworks/Python.framework/Versions/3.10/bin:$PATH" >> $GITHUB_ENV
          echo PATH="/Library/Frameworks/Python.framework/Versions/3.11/bin:$PATH" >> $GITHUB_ENV
          echo PATH="/Library/Frameworks/Python.framework/Versions/3.12/bin:$PATH" >> $GITHUB_ENV

      - name: Install system dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --user --upgrade ansible molecule-plugins[vagrant] tox
          vagrant plugin install vagrant-vbguest

      - name: Run tox
        run: |
          tox -vv
