---
name: Molecule testing workflow
on:
  workflow_dispatch:

jobs:
  Tox:
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set env variables
        run: |
          echo "/Users/runner/Library/Python/3.10/bin" >> $GITHUB_PATH
          echo "/Users/runner/Library/Python/3.11/bin" >> $GITHUB_PATH
          echo "/Users/runner/Library/Python/3.12/bin" >> $GITHUB_PATH
          echo "/Library/Frameworks/Python.framework/Versions/3.10/bin" >> $GITHUB_PATH
          echo "/Library/Frameworks/Python.framework/Versions/3.11/bin" >> $GITHUB_PATH
          echo "/Library/Frameworks/Python.framework/Versions/3.12/bin" >> $GITHUB_PATH
          echo "$PATH"

      - name: Install system dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --user --upgrade ansible ansible-lint molecule-plugins[vagrant]
          vagrant plugin install vagrant-vbguest

      - name: Run tox
        run: |
          ansible-lint
          molecule test
